### PR TITLE
Back end

### PR DESCRIPTION
**Pull request by ChagantiChandrakala**
[backend_json.zip](https://github.com/prernawaghray/GL-TechDocs/files/9819524/backend_json.zip)

### CODE REVIEW

**Comment by ChagantiChandrakala** [comment]
[Authentication folder.zip](https://github.com/prernawaghray/GL-TechDocs/files/9820536/Authentication.folder.zip)

**Comment by ChagantiChandrakala** [comment]
[login_logout_getprofile (2).zip](https://github.com/prernawaghray/GL-TechDocs/files/9843819/login_logout_getprofile.2.zip)

**Comment by minii-source** [comment]
[Delete_code.zip](https://github.com/prernawaghray/GL-TechDocs/files/9847049/Delete_code.zip)

**Comment by naseerp** [comment]
[forget_password.zip](https://github.com/prernawaghray/GL-TechDocs/files/9879457/forget_password.zip)

**Pull request closed without merging**
